# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        path: server/chatbot.api
    - name: Restore dependencies
      run: dotnet restore chatbot.api.sln
    - name: Build
      run: dotnet build chatbot.api.sln --no-restore
    - name: Test
      run: dotnet test chatbot.api.sln --no-build --verbosity normal
